-- Create portfolio_stocks table
CREATE TABLE IF NOT EXISTS portfolio_stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code VARCHAR(20) NOT NULL,
    stock_name VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(stock_code)
);

-- Add some initial data (optional, can be empty)
INSERT INTO portfolio_stocks (stock_code, stock_name)
VALUES 
    ('600519', '贵州茅台'),
    ('00700', '腾讯控股'),
    ('300750', '宁德时代')
ON CONFLICT (stock_code) DO NOTHING;
